# Generated by Django 3.1.2 on 2020-10-30 23:48

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201030_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=10, max_length=10, unique=True),
        ),
    ]
