# Generated by Django 3.1.2 on 2020-10-30 23:49

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notebook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=10, max_length=10, null=True, unique=True),
        ),
    ]
