# Generated by Django 3.1.2 on 2020-11-11 18:27

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=15, max_length=15, unique=True),
        ),
    ]
